weba:
  image: node-hello
  expose:
    - 80

webb:
  image: node-hello
  expose:
    - 80

webc:
  image: node-hello
  expose:
    - 80

haproxy:
  image: million12/haproxy
  volumes:
    - "./haproxy:/etc/haproxy/"
  links:
    - weba
    - webb
    - webc
  ports:
    - "80:80"
    - "70:70"

  expose:
    - "80"
    - "70"
