web:
  image: node-hello
  links:
    - db
  environment:
    - DATABASE_URL=postgres://db:5432

haproxy:
  image: eeacms/haproxy
  links:
    - web
  ports:
    - "80:80"
    - "1936:1936"

db:
  image: postgres
  ports:
    - "5432"
  volumes:
    - /etc/postgresql
    - /var/log/postgresql
    - /var/lib/postgresql
