web:
  build: node-hello
  expose:
    - 80

haproxy:
  image: million12/haproxy
  volumes:
    - "./haproxy:/etc/haproxy/"
  links:
    - web
  ports:
    - "80:80"
    - "70:70"
  expose:
    - "80"
    - "70"
